export const SYSTEM_CREATOR_ID = 'system'

export const BEATS_PER_BAR = {
  4: 4,
  3: 3
}

export const ERROR_CODES = {
  NOT_FOUND: 'NOT_FOUND',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INVALID_YOUTUBE_ID: 'INVALID_YOUTUBE_ID',
  YOUTUBE_VIDEO_TOO_LONG: 'YOUTUBE_VIDEO_TOO_LONG',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_SONG_ID_ERROR: 'INVALID_SONG_ID_ERROR',
  INVALID_VERSION_ID_ERROR: 'INVALID_VERSION_ID_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  EMAIL_ALREADY_TAKEN: 'EMAIL_ALREADY_TAKEN',
  FEATURE_UNAVAILABLE: 'FEATURE_UNAVAILABLE',
  UNKNOWN: 'UNKNOWN'
}

export const HTTP_CODES = {
  OK: 200,
  CREATED: 201,
  NOT_FOUND: 404,
  BAD_REQUEST: 400,
  CONFLICT: 409,
  NOT_IMPLEMENTED: 401,
  TOO_MANY_REQUESTS: 429,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503
}

// Simplified job state
export const JOB_STATUS = {
  waiting: 'waiting',
  failed: 'failed',
  completed: 'completed',
  processing: 'processing'
}
